CREATE OR REPLACE VIEW HIGH_SALARY_EMP AS
SELECT EMPLOYEE_NUMBER,
       EMPLOYEE_NAME,
       SALARY
FROM EMPLOYEE
WHERE SALARY > 60000;

CREATE OR REPLACE VIEW LOW_SALARY_EMP AS
SELECT EMPLOYEE_NUMBER,
       EMPLOYEE_NAME,
       SALARY
FROM EMPLOYEE
WHERE SALARY < 60000;

CREATE OR REPLACE VIEW TOP3_SALARY_EMP AS
SELECT EMPLOYEE_NUMBER,
       EMPLOYEE_NAME,
       SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC
LIMIT 3;
